### ISSUE TITLE
Ensure endpoints for wordpress are the same.

### ISSUE THREAD

**Issue by EvanFriday** [CiTR/djland#235]
- [ ] Show
- [ ] Special broadcast
- [ ] Playsheets

**Comment by citrtech** [comment]
Appears to be changeable in the wp_config file on the wordpress - define the API base, then wordpress concatenates /specialbroadcast/ or /show/ or /playsheets to it as needed. So long as we stick to djland.citr.ca/api/public/ as the base and then keep then relative endings at the same points we should be fine. 

If we do move /show/ to a different endpoint then we just have to update the djland_connector files to expect that.

This only needs to be done on a config file basis so this isn't something that we need to code in right now.

**Comment by scottpidzarko** [comment]
Actually finished now with this @EvanFriday
