### ISSUE TITLE
Checkboxes are wonky on tagging and approving tags sidebar

### ISSUE THREAD

**Issue by scottpidzarko** [CiTR/djland#276]
Noted as a problem with femcon/cancon/local checkboxes, but check behavior of all 6

- [ ] Confirm that they are being loaded correctly in tagging sidebar
- [ ] Confirm that they are being loaded correctly in approving tags sidebar
- [ ] Confirm that they are being saved correctly in tagging sidebar
- [ ] Confirm that they are being saved correctly in approving tags sidebar

**Comment by scottpidzarko** [comment]
@michaeladria you said you fixed this?

**Comment by michaeladria** [comment]
Fixed
