### ISSUE TITLE
Submit_online page and manual submissions need to either accept only mp3s or transcode to mp3

### ISSUE THREAD

**Issue by scottpidzarko** [CiTR/djland#278]
The library page code that makes it into 30s fragments relies on them only ever being mp3s.

Transcoding files if they are not mp3s is easy in php. Just:

- put them in the php temp directory 
- trigger ffmpeg with a php exec() call.to transcode to mp3 with the output fillename being the same as the input, with the output in the proper location for the files.
- Delete the untranscoded filles out of the temp directory with unlink()

Have a look at the tempnam(), sys_get_temp_dir(), get_file_contents(), file_put_contents(), and unlink() functions for logistics of moving data in/out of the php temporary directory.

**Comment by michaeladria** [comment]
Converts to mp3.
